name: Step 1, Copilot Extension in a Codespace

# This step triggers after push to main#devcontainer.json.
# This workflow updates from step 1 to step 2.

# This will run every time we main#devcontainer.json
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    paths:
      - ".devcontainer/devcontainer.json"
    branches:
      - main

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # The purpose of this job is to output the current step number
  # (retreived from the step file). This output variable can
  # then be referenced in other jobs and used in conditional.
  # expressions.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_add_devcontainer:
    name: On Add Devcontainer
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 1 }}

    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4

      # Verify the learner added the file contents.
      - name: Check workflow contents, jobs
        uses: skills/action-check-file@v1
        with:
          file: ".devcontainer/devcontainer.json"
          search: "GitHub\\.copilot"

      # In README.md, switch step 1 for step 2.
      - name: Update to step 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2

      # Commits pushed by an Action will not create a new workflow run. To work
      # around this, create a repository_dispatch event to ensure that GitHub
      # Classroom's autograding workflow runs on the commit created by
      # skills/action-update-step.
      # Reference: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
      - name: Trigger autograding workflow
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/dispatches" \
            -f "event_type=autograde"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
